import { ArrowRight, CalendarDays, CircleCheck, Package, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { getOrders } from '../../api/orderApi'
import { getPickups } from '../../api/pickupApi'
import { useAuth } from '../../context/AuthContext'
import LoadingSpinner from '../../components/common/LoadingSpinner'
import OrderCard from '../../components/order/OrderCard'
import PickupCard from '../../components/pickup/PickupCard'

export default function DashboardPage() { const { user } = useAuth(); const [orders, setOrders] = useState([]); const [pickups, setPickups] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { Promise.all([getOrders(), getPickups()]).then(([ordersResponse, pickupResponse]) => { setOrders(ordersResponse.data.data.orders); setPickups(pickupResponse.data.data.pickups) }).finally(() => setLoading(false)) }, []); if (loading) return <LoadingSpinner label="Preparing your dashboard" />; return <main className="app-page page-shell"><div className="welcome-row"><div><p className="eyebrow">your folded space</p><h1>Good morning, {user?.name?.split(' ')[0] || 'there'}<span className="brand-dot">.</span></h1><p className="muted">A little more room in your day starts here.</p></div><Link className="button button-yellow" to="/schedule"><Plus size={17} /> New pickup</Link></div><div className="stat-grid"><div className="stat-card"><span className="stat-icon"><Package size={18} /></span><strong>{orders.length}</strong><span>total orders</span></div><div className="stat-card"><span className="stat-icon"><CalendarDays size={18} /></span><strong>{pickups.filter((p) => p.status !== 'completed').length}</strong><span>active pickups</span></div><div className="stat-card"><span className="stat-icon"><CircleCheck size={18} /></span><strong>{orders.filter((o) => o.status === 'delivered').length}</strong><span>delivered</span></div></div><div className="dashboard-columns"><section><div className="section-heading compact"><h2>Latest order</h2><Link className="text-link" to="/orders">See all <ArrowRight size={15} /></Link></div>{orders.length ? <OrderCard order={orders[0]} /> : <div className="empty-state"><Package size={28} /><h3>Your next clean start</h3><p>No orders yet. Book a pickup and we’ll take it from here.</p><Link className="text-link" to="/schedule">Book a pickup <ArrowRight size={15} /></Link></div>}</section><section><div className="section-heading compact"><h2>Upcoming pickup</h2></div>{pickups.length ? <PickupCard pickup={pickups[0]} /> : <div className="empty-state pale"><CalendarDays size={28} /><h3>Nothing on the calendar</h3><p>Choose a window that works for you.</p></div>}</section></div></main> }
